ahcis-rds/study_finder

app/controllers/admin/system_controller.rb, app/views/admin/system/edit.html.haml, app/views/studies/index.html.haml, db/migrate/20191217194422_add_display_keywords_to_system_infos.rb, db/schema.rb
This adds a new option in the system administration section to indicate
whether trial keywords should be displayed in search results. This
defaults to `true` to maintain backward compatibility.
When this option is set to `false` keywords are still stored and used
for searches, but they are not displayed in results.
Note that because search results are the only place in the application
that these keywords are displayed, if this option is turned off you
can't view a trial's keywords (even in the admin interface). We may
eventually want to add an administrative trial view so keywords (and
all associated trial data) can be viewed by system administrators.
=> Make trial keywords display optional

app/models/study_finder/trial.rb
This prevent elasticsearch from trying to index keyword rows that don't actually have a keyword.
=> Fix nil keywords

app/controllers/admin/groups_controller.rb, app/views/admin/groups/_form.html.haml, spec/controllers/admin/groups_controller_spec.rb
This reworks the subgroup saving. It was using the deprecated form of
`delete_all`. `delete_all` has been removed altogether because the
existing code had a few other issues:
- Subgroups would not save if nothing else on the group changed.
- Subgroup saving was wrapped in `params[:tags].nil?` but this is never
the case in the real world. Empty tags came through as `[""]`.
This change builds up the set of subgroups on every save and calls an
explicit `save` on the parent Group. I'd rather have used nested
attributes on this, but didn't want to spend time reworking the select2
interface.
=> Fix saving of Groups/Subgroups

app/controllers/studies_controller.rb
This was missed in the Rails upgrade from 4.2. `head :ok` is now preferred over `render nothing: true` for producing an HTTP 200 header-only response. `render nothing: true` was looking for a template and was returning an error because none exists for this route.
=> Update js responses for emails

lib/connectors/ctgov.rb
The `studyfinder:ctgov:reload_all` task is meant to throw away all
studies and reload all history from clinicaltrials.gov. Since
Condition/Group mappings are completely standalone, this operation also
throws away any time-consuming manual entry that has been done. This
data is completely separate from study data, so it seems better to have
it remain even when studies are fully reloaded from source.
=> Don't clear Condition and ConditionGroup on reload_all

app/controllers/admin/system_controller.rb, app/views/admin/system/edit.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_search_form.html.erb, db/migrate/20200622195327_add_category_config_to_system_infos.rb, db/schema.rb, spec/controllers/admin/system_controller_spec.rb, spec/views/search/embed.html.erb_spec.rb
Creates a mechanism for administrators to configure whether or not Categories are displayed within the site. It creates a boolean in the system_infos table to key off of. If true (default value) the site will operate as it has historically, however if false the "browse by categories" button will be hidden from the search form and clicking the "search for a study" nav item will bring users directly to the study results page.
=> Category (group) toggle configuration

app/helpers/studies_helper.rb, app/views/shared/_refine_search.html.erb, app/views/shared/_search_form.html.erb, app/views/studies/index.html.erb
Relabeling "Gender" to "Sex" as 'sex' is a biological/clinical term and 'gender' generally refers to an identity. This change is only front-facing. The back-end still references gender because the database column and ctgov attribute are both 'gender'.
=> Relabeling gender as sex as sex is a biological term.

app/assets/stylesheets/pages/studies.css.scss, app/controllers/admin/system_controller.rb, app/controllers/studies_controller.rb, app/views/admin/system/edit.html.erb, app/views/studies/_modals.html.erb, app/views/studies/index.html.erb, app/views/studies/show.html.erb, config/routes.rb, db/migrate/20200710133712_add_study_show_config_to_system_infos.rb, db/schema.rb, spec/controllers/studies_controller_spec.rb, spec/views/search/embed.html.erb_spec.rb
This PR adds a configurable study show page to StudyFinder. The default action is to disable the show page to preserve historic functionality. Administrators may enable the show page from the System Administration interface.
=> Add Configurable Study Show Page

app/assets/stylesheets/pages/admin.css.scss, app/assets/stylesheets/pages/studies.css.scss, app/controllers/admin/system_controller.rb, app/controllers/studies_controller.rb, app/helpers/studies_helper.rb, app/models/system_info.rb, app/models/trial.rb, app/models/trial_attribute_setting.rb, app/views/admin/system/edit.html.erb, app/views/layouts/application.html.erb, app/views/studies/index.html.erb, app/views/studies/show.html.erb, db/migrate/20200723212151_create_trial_attribute_settings.rb, db/schema.rb, db/seeds.rb, db/seeds/trial_attribute_settings.json
Adding attribute display options for study index/show pages; configurable through the system admin interface. Initial attribute configuration should mirror existing functionality. 
*Note: overall_status has been added to the study index page and  the Trial.rb 'as_indexed_json' method. As a result the site must be re-indexed.
=> Study Attribute Toggles

app/controllers/admin/trials_controller.rb, app/helpers/studies_helper.rb, app/models/trial.rb, app/views/admin/trials/edit.html.erb, app/views/studies/index.html.erb, app/views/studies/show.html.erb, db/migrate/20200928205903_add_contact_url_to_trials.rb, db/schema.rb
Adding a contact url option for each trial. This option can be provided on import or as an override option from within the admin/trial administration interface.
Behavior: In the event a contact_url or contact_url_override value is present on a Trial, the "Contact the Study Team" button will link to the provided URL instead of opening the contact modal.
=> Adding Contact URL to Trials

app/mailers/study_mailer.rb, spec/mailers/study_mailer_spec.rb
=> Include user-provided email in StudyMailer

app/controllers/studies_controller.rb, app/models/group.rb, app/models/trial.rb, app/models/vw_group_trial_count.rb, config/analysis/synonyms.txt, spec/controllers/studies_controller_spec.rb
During setup and/or development a group that contains no conditions
would previously cause an error (#65). This fixes the error, but also
changes the behavior of empty groups.
Before this change the application would check for the no conditions
case and instead return all studies. This is somewhat jarring/unexpected
when you create a new group and see that it contains all studies (both
in the results and the study counts). I think it makes more sense to
make the default to be empty, and only include studies once matching
conditions are added.
StudiesController#index was simplified a bit too during this change. I
think this method had grown over time and built up some unneeded
complexity. A new top-level `Trial.execute_search` (`search` is already
taken by the elasticsearch gem) was …
=> Gracefully handle empty groups

config/environments/production.rb, config/environments/staging.rb
This defaults to using an SMTP server for outbound email, configured via the `smtp_host` environment variable. This was lost at some point through the Rails upgrade.
=> Default to SMTP for outbound email

app/assets/javascripts/views/modals.js
This file used to be included at the end of the page. Now that it's in the head we need this to make sure the DOM elements exist before these events are attached.
=> Wrap modals.js in document loaded function

lib/parsers/ctgov.rb, spec/parsers/ctgov_spec.rb
This changes the ctgov importer to always consider the current
`overall_status` value when determining visibility.
Previously the visible flag was only updated it the parser detected a
change in the overall status. We've found that in production these
can get out of sync; the overall_status becomes something other than
"Recruiting", but the visible flag remains set to true.
The deployment of this change should be accompanied with a one-time
manual update of all trials' visibility flag and a re-index to catch
trials that may no longer be returned from the clinicaltrials.gov
import.
=> Always set visible flag based on current values

app/controllers/admin/trials_controller.rb, app/models/trial.rb, app/views/admin/trials/recent_as.html.erb, app/views/admin/trials/recent_as.xls.erb
Expanding the "Recent Trials" report to optionally search by only recently added trials (created_at instead of updated_at). The default and historic behavior remain consistent. Also adding the Date Imported column to the view and xls export.
=> Update - Recent Trials Report

README.md, config/initializers/wicked_pdf.rb
Adding wickedpdf initializer. Specifying path to the wkhtmltopdf binary via an environment variable (set this in application.yml). Also setting "use_xvfb" to true so wkhtmltopdf commands are wrapped within an xvfb-run command (simulates an X server). Updating readme to include example environment variable.
=> WickedPDF Deploy Fix

app/assets/javascripts/studyfinder.js, app/controllers/studies_controller.rb, app/models/trial.rb, config/routes.rb
This was mostly just a routing problem. When the study show route was added, it started snatching up requests to `/studies/typeahead`. I also took the opportunity to push the complexity of the suggestions structure up into the Trial model. `Trial.typeahead` will now just returns an array of strings instead of the raw Elasticsearch response.
This fix makes the typeahead javascript work again, but the there's still a lot of room for improvement in the quality of suggestions we're getting. This is just step 1.
=> Fix typeahead search suggestions

app/controllers/studies_controller.rb
These parameters were not included in the permitted params so they were not making it to the search method.
This was missed in the Rails upgrade.
=> Fix children and adult search filters

app/models/trial.rb, spec/models/trial_spec.rb
Intervention data from clinicaltrials.gov comes with a type, name, and description. Data from other sources may just have a single value. This change handles cases where no type data is available.
This change requires a re-index.
=> Handle basic intervention data

app/helpers/studies_helper.rb, app/models/trial.rb
This field has always been missing. In the wild it's caused us (and others) to pack the contact_last_name field with both the first and last name in order to display a full name.
This change requires a re-index.
=> Index and display contact first name

app/views/categories/index.html.erb, app/views/contact/index.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_refine_search.html.erb
Updating the "Contact Us" functionality. "Contact Us" becomes "Help" and users are prompted with a FAQ section before the contact form is displayed.
Adding the "refine search" box from study results page to the Categories page as it gives users another method to search for studies.
Updating layout elements according to wishes of the studyfinder team.
=> FAQ and Layout Updates

app/models/trial.rb
This field is usually not displayed in search results, but adding allows
users to search on a PI's email address (or whatever is populated here)
in order link to a list of studies for a given PI.
=> Search trial.pi_id

app/views/studies/index.html.erb
Updating buttons based on feedback from the studyfinder team.
*Removing "View Study" button as the title is hyperlinked and this is superfluous.
*Updating email me button to the more concise "share via email"
*Reordering "contact the study team" and "share via email" buttons so the more important of the two is featured more prominently
*Updating ctgov button link to be consistent with the study show page.
=> Button Updates for Study Index

app/controllers/admin/system_controller.rb, app/views/admin/system/edit.html.erb, app/views/contact/index.html.erb, db/migrate/20210114144059_add_faq_to_system_infos.rb, db/schema.rb
Adding FAQ description to system_infos. Rendering this content before the contact form on the "Help" page if content is present. Now the studyfinder team may update the contents periodically without developer intervention.
=> Dynamic FAQ

app/assets/stylesheets/pages/studies.css.scss, app/helpers/studies_helper.rb, app/views/studies/_description.html.erb, app/views/studies/index.html.erb, app/views/studies/show.html.erb
In the event a study description is more than 500 characters this will truncate the description and add a popover with the entire description contents to the page. This is to prevent super-long descriptions from disrupting the page layout and user experience.
=> Study Description Formatting

app/assets/javascripts/views/modals.js, app/views/contact/index.html.erb, app/views/studies/_modals.html.erb
This makes several updates to the contact and email forms to make these clearer and easier to use:
- Instructions have been updated to explain what the forms do.
- Form labels have been updated based on feedback that these—along with the previous instructions—could be confusing.
- Required field indicators have been expanded to "required"
- Form labels have been semantically connected to the form controls (the `for` attribute)
There may be some adjustments to the language I've chosen here, but I think this is a move in the right direction and increases the usability and accessibility of these forms.
=> Update contact forms

app/views/shared/_flash.html.erb
These have been invisible since the Bootstrap 4 upgrade. The
fade-to-appear classes have changed from `fade in` to `fade show`.
Fixes #88.
=> Fix flash messages

app/controllers/admin/trials_controller.rb
Just viewing the edit form should not re-import anything. It should have
no side-effects. The trial edit form is used to override certain values and 
re-importing on the edit form load completely cancels this out. If you
override a value, it saves, redirects you to the edit form, and un-does
the change you just made.
=> Don't import trials when loading edit form

app/controllers/admin/trials_controller.rb, app/models/trial.rb, app/views/admin/trials/edit.html.erb, db/migrate/20210302004918_add_healthy_volunteers_override_to_trials.rb, db/schema.rb, lib/parsers/ctgov.rb, spec/models/trial_spec.rb
This allows administrators to override the `accepts healthy volunteers?`
field for a trial. Occasionally, studies that will meet their healthy
volunteer enrollment goals and will want to continue recruiting
non-healthy participants without modifying the entry in clinicaltrials.gov.
I don't love that this solution introduces two new database columns and
changes the surface area of the importer. However based on recent
conversations, I expect more of these kinds of overrides to be
introduced. When we get some more to implement I'd like to explore
building a more robust but simple override mechanism that plays nicely
with Elasticsearch.
=> Add healthy_volunteers override option

README.md, app/models/trial.rb, app/views/studies/_clinicaltrialsgov_button.html.erb, app/views/studies/index.html.erb, app/views/studies/show.html.erb, app/views/study_mailer/email_me.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, spec/models/trial_spec.rb
Not all studies will have an NCT number in the `system_id` field. While eventually we'll want to build some new data structures to more gracefully handle data imports from multiple systems, this change will let us immediately accommodate Mayo studies on healthstudiesmn.org.
This seemingly simple change sprawled a bit from the buttons. Because the "share via email" mailer included a clinicaltrials.gov link, we've just replaced it with a link to StudyFinder itself (either the show page if enabled, or a single-item search). Rendering this link URL in the mailer requires us to introduce a new environment variable to set the host (and optionally the protocol): `DEFAULT_URL_HOST`.
=> Conditionally render clinicaltrials.gov button

app/models/trial.rb, db/migrate/20210402161847_add_added_on_to_trials.rb, db/schema.rb, lib/parsers/ctgov.rb, spec/models/trial_spec.rb
The search results previously had no explicit ordering. Because we're
using `match_all` queries we dont' get a relevancy score from
Elasticsearch.
This change introduces a new column on Trial: added_on. We can't use an
existing date (like created_at) because trials can be periodically
completely refreshed. Clinicaltrials.gov has a date that seems
appropriate for this use (date_first_posted) so we're defaulting to
that. This can of course be overridden with dates from other integrating
systems like OnCore.
=> Sort search results by newest studies first

app/controllers/api/studies_controller.rb, app/controllers/api_controller.rb, app/models/api_key.rb, app/models/trial.rb, app/views/api/studies/index.json.jbuilder, app/views/api/studies/show.json.jbuilder, config/routes.rb, db/migrate/20210108230551_create_api_keys.rb, db/schema.rb, spec/controllers/api/studies_controller_spec.rb, spec/models/api_key_spec.rb, spec/models/trial_spec.rb
This API was extracted from UMN's StudyFinder. It allows external processes to update basic Trial data and keywords from outside the application. It's meant to be used to augment the CT.gov data with data from other sources (like CTMS, IRB, etc).
=> Add trial API

README.md
Now that that database views have been removed (in  #130) we can just
`rails db:setup` instead of manually doing a `db:create`, `db:migrate`,
and `db:seed`. The views were previously not present in `schema.rb`, which
`db:setup` uses.
This PR depends on #130.
=> Update database initialization instructions

.github/workflows/ci.yml, README.md, spec/rails_helper.rb
This enables CI via Github Actions. It's configured to build any push from any branch right now, which I think is fine for the amount of activity this project sees.
=> Enable CI via GitHub actions

app/views/admin/trials/recent_as.html.erb
This report is often used to know when to reach out to study teams to
let them know their study is appearing on StudyFinder. Without this
visibility flag, admins have to manually search each of these to
determine if they're actually visible in StudyFinder.
=> Add visible? column to recent trials report

lib/connectors/ctgov.rb, lib/tasks/ctgov.rake, spec/connectors/ctgov_spec.rb, spec/factories/parser.rb, spec/factories/trial.rb
Added a task to un-publish trials that are no longer in the list of recruiting trials for the location that is being used to pull from clinicaltrials.gov.
- Refactored ctgov connector nct_ids_for_location method to use current ct.gov API. Also uses recursion without passing arrays of IDs into a new method invocation for memory benefits.
- In same method, include filter for only recruiting studies at location.
- Allow cleanup_stray_trials and stray_trials to accept an argument of an array of IDs that should be considered "still recruiting"; this can be leveraged for testing bc there isn't a great way to mock ct.gov API responses given the current state of coupling in the connector.
- Tests for these updates.
=> Address expiry of studies from clinicaltrials.gov

README.md, app/views/studies/_clinicaltrialsgov_button.html.erb, docker-compose.yml, lib/connectors/ctgov.rb, lib/parsers/ctgov.rb, lib/tasks/ctgov.rake, spec/parsers/ctgov_spec.rb
Refactor to use v2 API and update URLs that referenced "classic" site for study pages.
Connector changes:
1. Recurse over its pages of results -- no longer an option to return more than 100 studies at once when searching with location etc. criteria.
2. Show status messages for both current "page" and overall.
3. Fix #clear, which had not been updated to delete TrialSubgroups when those were added (hence was failing to delete Trials with a reference error).
Parser changes:
1. Major changes to switch from XML/xpath to the new JSON format for API responses.
2. Don't re-fetch data for each study individually, data for studies loads in each "page" in the connector and that data for each study is included in the parser object initialization (each parser instance represents handling of data for …
=> Update ct.gov connector and parser for ct.gov API v2
